# string templates

QUESTIONS = [
    'Are you suffering from {}?',
    'Are you plagued by {}?',
    'Is {} keeping you up at night?',
    'Worried you might have {}?',
    'You don\'t have to deal with {} alone.',
    'Help relieve {}.',
    'Want to reduce you risk of {}?',
    'For moderate to severe {}',
    'Do you need gentle, predictable relief from {}?',
    '{} can be serious!',
    'Have {}, {}, and {}?',
    'Myth: there\'s nothing you can do about your {}. Fact: You have options!',
    'You still have {}!?',
    'Is your {} a nightmare?',
    'Don\'t let {} interfere with your life',
    'Is {} part of your life?',
    'Have you been craving relief from {}?',
]

ANSWERS = [
    u'Ask your doctor about {}\u00AE today!',
    u'Try {}\u00AE!',
    u'{}\u00AE can help!',
    u'Ask your doctor if {}\u00AE is right for you!',
    u'It\'s time for {}\u00AE',
    u'Discover {}\u00AE',
]

# words used to generate diseases

BODY_PARTS = [
    # Please keep list alphabetical to keep verifying duplicates easy
    'ankle',
    'bladder',
    'brainstem',
    'bicep',
    'buttock',
    'cornea',
    'elbow',
    'eyebrow',
    'eyelid',
    'forehead',
    'intestine',
    'knee',
    'knuckle'
    'metacarpal',
    'nostril',
    'ossicle',
    'septum',
    'shin',
    'shoulder',
    'spleen',
    'sternum',
    'stomach',
    'thumb',
    'toenail',
    'tongue',
    'wrist',
]

ADJECTIVES = [
    # Please keep list alphabetical to keep verifying duplicates easy
    'achy',
    'aggressive',
    'agitated',
    'distressed',
    'drunken',
    'gooey',
    'inflexible',
    'lazy',
    'herniated',
    'hyperactive',
    'hyperextended',
    'jumpy',
    'leaky',
    'nasty',
    'overexerted',
    'oversensitive',
    'pompous',
    'restless',
    'sarcastic',
    'seasonal',
    'spiritless',
    'sprained',
    'stabbing',
    'strained',
    'tender',
    'torturous',
    'throbbing'
    'twitchy',
    'vague',
    'vulgar',
]

SUPERLATIVES = [
    # Please keep list alphabetical to keep verifying duplicates easy
    'above-average',
    'acute',
    'constant',
    'compulsive',
    'dreadful',
    'excessive',
    'intense',
    'severe',
    'superfluous',
    'troublesome',
    'unwanted',
]

SYMPTOMS = [
    # Please keep list alphabetical to keep verifying duplicates easy
    'angst',
    'belching',
    'cynicism',
    'delusion',
    'diarrhea',
    'discharge',
    'dizziness',
    'drainage',
    'drooling',
    'narcissism',
    'exhaustion',
    'fainting',
    'fever'
    'flatulence',
    'impulsiveness',
    'laughter',
    'nausea',
    'mood swings',
    'sweating',
    'rash',
    'ringing in the ears',
    'snoring',
    'vertigo',
    'vomiting',
]
# from https://simple.wikipedia.org/wiki/List_of_colors

COLORS = [
    'Amaranth',
    'Amber',
    'Amethyst',
    'Apricot',
    'Aquamarine',
    'Azure',
    'Baby blue',
    'Beige',
    'Black',
    'Blue',
    'Blue-green',
    'Blue-violet',
    'Blush',
    'Bronze',
    'Brown',
    'Burgundy',
    'Byzantium',
    'Carmine',
    'Cerise',
    'Cerulean',
    'Champagne',
    'Chartreuse green',
    'Chocolate',
    'Cobalt blue',
    'Coffee',
    'Copper',
    'Coral',
    'Crimson',
    'Cyan',
    'Desert sand',
    'Electric blue',
    'Emerald',
    'Erin',
    'Gold',
    'Gray',
    'Green',
    'Harlequin',
    'Indigo',
    'Ivory',
    'Jade',
    'Jungle green',
    'Lavender',
    'Lemon',
    'Lilac',
    'Lime',
    'Magenta',
    'Magenta rose',
    'Maroon',
    'Mauve',
    'Navy blue',
    'Ocher',
    'Olive',
    'Orange',
    'Orange-red',
    'Orchid',
    'Peach',
    'Pear',
    'Periwinkle',
    'Persian blue',
    'Pink',
    'Plum',
    'Prussian blue',
    'Puce',
    'Purple',
    'Raspberry',
    'Red',
    'Red-violet',
    'Rose',
    'Ruby',
    'Salmon',
    'Sangria',
    'Sapphire',
    'Scarlet',
    'Silver',
    'Slate gray',
    'Spring bud',
    'Spring green',
    'Tan',
    'Taupe',
    'Teal',
    'Turquoise',
    'Violet',
    'Viridian',
    'White',
    'Yellow',
]
