# string templates

QUESTIONS = [
  'Are you suffering from {}?',
  'Is your {} keeping you up at night?',
  'Worried you might have {}?',
  'You don\'t have to deal with {} alone.',
]

ANSWERS = [
    'Ask your doctor about {} today!',
    'Try {}!',
    '{} can help!',
    'Ask your doctor if {} is right for you!',
]

# words used to generate diseases

BODY_PARTS = [
    'eyebrow',
    'elbow',
    'toenail',
    'knee',
    'metacarpal',
    'bladder',
    'spleen',
    'intestine',
    'brainstem',
    'ossicle',
    'cornea',
    'buttock',
    'nostril',
]

ADJECTIVES = [
    'aggressive',
    'lazy',
    'inflexible',
    'pompous',
    'sarcastic',
    'vague',
    'restless',
    'achy',
    'drunken',
    'oversensitive',
    'twitchy',
    'vulgar',
    'sprained',
    'strained',
    'overexerted',
    'herniated',
]

SUPERLATIVES = [
    'excessive',
    'superfluous',
    'constant',
    'above-average',
    'intense',
    'troublesome',
    'compulsive',
]

SYMPTOMS = [
    'flatulence',
    'laughter',
    'fainting',
    'exhaustion',
    'angst',
    'cynicism',
    'vomiting',
    'nausea',
    'vertigo',
    'dizziness',
    'ringing in the ears',
]
# from https://simple.wikipedia.org/wiki/List_of_colors

COLORS = [
    'Amaranth',
    'Amber',
    'Amethyst',
    'Apricot',
    'Aquamarine',
    'Azure',
    'Baby blue',
    'Beige',
    'Black',
    'Blue',
    'Blue-green',
    'Blue-violet',
    'Blush',
    'Bronze',
    'Brown',
    'Burgundy',
    'Byzantium',
    'Carmine',
    'Cerise',
    'Cerulean',
    'Champagne',
    'Chartreuse green',
    'Chocolate',
    'Cobalt blue',
    'Coffee',
    'Copper',
    'Coral',
    'Crimson',
    'Cyan',
    'Desert sand',
    'Electric blue',
    'Emerald',
    'Erin',
    'Gold',
    'Gray',
    'Green',
    'Harlequin',
    'Indigo',
    'Ivory',
    'Jade',
    'Jungle green',
    'Lavender',
    'Lemon',
    'Lilac',
    'Lime',
    'Magenta',
    'Magenta rose',
    'Maroon',
    'Mauve',
    'Navy blue',
    'Ocher',
    'Olive',
    'Orange',
    'Orange-red',
    'Orchid',
    'Peach',
    'Pear',
    'Periwinkle',
    'Persian blue',
    'Pink',
    'Plum',
    'Prussian blue',
    'Puce',
    'Purple',
    'Raspberry',
    'Red',
    'Red-violet',
    'Rose',
    'Ruby',
    'Salmon',
    'Sangria',
    'Sapphire',
    'Scarlet',
    'Silver',
    'Slate gray',
    'Spring bud',
    'Spring green',
    'Tan',
    'Taupe',
    'Teal',
    'Turquoise',
    'Violet',
    'Viridian',
    'White',
    'Yellow',
]
